# Generated by Django 4.1.2 on 2022-10-23 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog_post_restful", "0002_alter_bloglist_author_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloglist",
            name="author_name",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bloglists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
